variable "dashboard_name" {}
variable "rg_name" {}
variable "rg_location" {}
variable "core_subscription_id" {}
variable "azsawestagingcore_name" {}
variable "azsawestagingcore_id" {}
variable "batch_name" {}
variable "batch_id" {}
variable "datalake_name" {}
variable "datalake_id" {}
variable "keyvault_id" {}
variable "keyvault_name" {}
variable "data_factory_id" {}
variable "data_factory_name" {}
variable "fapp_storage_acc_name" {}
variable "fapp_storage_acc_id" {}
variable "functionapp_name" {}
variable "functionapp_id" {}