variable "core_rg" {}
variable "environment" {}
variable "core_vnet" {}
variable "pe_subnet_name" {}
variable "core_function_app_subnet_name" {}
variable "batch_account_subnet_name" {}
variable "core_db_subnet" {}
variable "acr_private_dns_name" {}
variable "file_private_dns_zone_name" {}
variable "blob_private_dns_zone_name" {}
variable "table_private_dns_zone_name" {}
variable "queue_private_dns_zone_name" {}
variable "psql_private_dns_zone_name" {}
variable "fap_private_dns_zone_name" {}
variable "batch_private_dns_zone_name" {}
variable "keyvault_private_dns_zone_name" {}
variable "dns_rg" {}
variable "kcri_rg" {}
variable "backup_vault_name" {}
variable "soc_security_rg_name" {}
variable "loganalytics_workspace_name" {}
