variable "lss_functionapp_id" {}
variable "inv_wq_functionapp_id" {}
variable "crs_functionapp_id" {}
variable "inv_lss_functionapp_id" {}
variable "inv_ml_functionapp_id" {}
variable "ml_functionapp_id" {}
variable "log_analytics_workspace_id" {}
variable "core_eventhub_id" {}
variable "ch_eventhub_id" {}
variable "inv_postgresql_id" {}
variable "ch_postgresql_id" {}
variable "ch_container_registry_id" {}
variable "aks_id" {}
variable "batch_lss_account_id" {}
variable "batch_ml_account_id" {}
variable "sanursery_id" {}
variable "ml_hist_storage_id" {}
variable "lss_hist_storage_id" {}
variable "inv_storage_id" {}