variable "fw_policy_rule_cg_name" {}
variable "fw_policy_id" {}
variable "network_collection_rule_name" {}
variable "management_collection_rule_name" {}
variable "core_to_ch_rule_name" {}
variable "core_vnet_address_space" {}
variable "ch_vnet_address_space" {}
variable "ch_to_core_rule_name" {}
variable "core_to_kvap_rule_name" {}
variable "kvap_vnet_address_space" {}
variable "kvap_to_core_rule_name" {}
variable "core_to_sensor_rule_name" {}
variable "sensor_vnet_address_space" {}
variable "sensor_to_core_rule_name" {}
variable "gitlab_to_core_rule_name" {}
variable "gitlab_vnet_address_space" {}
variable "core_to_gitlab_rule_name" {}
variable "gitlab_to_sensor_rule_name" {}
variable "sensor_to_gitlab_rule_name" {}
variable "gitlab_to_ch_rule_name" {}
variable "ch_to_gitlab_rule_name" {}
variable "gitlab_to_kvap_rule_name" {}
variable "kvap_to_gitlab_rule_name" {}
variable "vpop_collection_rule_name" {}
variable "core_to_vpop_rule_name" {}
variable "vpop_address_space" {}
variable "vpop_to_core_rule_name" {}
variable "ch_to_vpop_rule_name" {}
variable "vpop_to_ch_rule_name" {}
variable "vpop_to_kvap_rule_name" {}
variable "kvap_to_vpop_rule_name" {}
variable "sensor_to_vpop_rule_name" {}
variable "vpop_to_sensor_rule_name" {}
variable "gitlab_to_vpop_rule_name" {}
variable "vpop_to_gitlab_rule_name" {}
variable "sensor_to_internet_rule_name" {}
variable "gitlab_to_internet_rule_name" {}
variable "function_app_sensor_to_internet_rule_name" {}
variable "batch_account_sensor_to_internet_rule_name" {}
variable "sensor_functionapp_subnet_prefixes" {}
variable "sensor_batch_account_subnet_address_prefixes" {}
variable "ml_function_app_subnet_address_prefixes" {}
variable "function_app_ml_to_internet_rule_name" {}
variable "ml_batch_account_subnet_address_prefixes" {}
variable "batch_account_ml_to_internet_rule_name" {}
variable "lss_batch_account_subnet_address_prefixes" {}
variable "batch_account_lss_to_internet_rule_name" {}
variable "function_app_lss_to_internet_rule_name" {}
variable "lss_function_app_subnet_address_prefixes" {}
variable "function_app_inv_to_internet_rule_name" {}
variable "inv_function_app_subnet_address_prefixes" {}



