variable "backup_vault_id" {}
variable "backup_vault_principal_id" {}
variable "storage_account_name" {}
variable "environment" {}
variable "location" {}
variable "sensor_rg_id" {}
variable "storage_account_id" {}
variable "vm_backup_vault_policy_name" {}
variable "shiny_vm_id" {}
variable "shiny_vm_name" {}
variable "sensor_rg_name" {}
variable "soc_security_rg_name" {}
variable "backup_vault_policy_name" {}
variable "shiny_vm_os_disk_name" {}
variable "backup_vault_name" {}
variable "management_subscription_id" {}
variable "sensor_rg_location" {}
variable "ARM_CLIENT_ID" {}
variable "ARM_CLIENT_SECRET" {}
variable "ARM_TENANT_ID" {}