variable "core_rg" {}
variable "core_rg_location" {}
variable "environment" {}
variable "az_pstgre_we_sensor_db_core" {}
variable "az_pstgre_we_sensor_db_core_version" {}
variable "core_db_subnet_id" {}
variable "pstgre_db_username" {}
variable "pstgre_db_password" {}
variable "az_pstgre_we_sensor_db_core_zone" {}
variable "pstgre_storage_mb" {}
variable "pstgre_storage_tier" {}
variable "pstgre_sku_name" {}
variable "azure_extensions_name" {}
variable "azure_extensions_values" {}
variable "tags" {}
variable "shared_preload_libraries_name" {}
variable "shared_preload_libraries_values" {}
variable "psql_private_dns_zone_id" {}
