variable "acr_private_dns_name" {}
variable "file_private_dns_zone_name" {}
variable "blob_private_dns_zone_name" {}
variable "table_private_dns_zone_name" {}
variable "queue_private_dns_zone_name" {}
variable "psql_private_dns_zone_name" {}
variable "fap_private_dns_zone_name" {}
variable "batch_private_dns_zone_name" {}
variable "keyvault_private_dns_zone_name" {}
variable "gitlab_resource_group_name" {}
variable "gitlab_vnet_name" {}
variable "eventhub_private_dns_name" {}
variable "dns_rg_name" {}
variable "aks_private_dns_zone_name" {}
variable "soc_security_rg_name" {}
variable "connectivity_vnet_name" {}
variable "connectivity_rg_name" {}
variable "firewall_name" {}
variable "firewall_policy_name" {}