variable "adf_name" {}
variable "core_rg_location" {}
variable "core_rg" {}
variable "storage_private_endpoint_name" {}
variable "storage_account_id" {}
variable "key_vault_id" {}
variable "datalake_private_endpoint_name" {}
variable "datalake_id" {}
variable "datalake_linked_name" {}
variable "datalake_url" {}
variable "keyvault_linked_name" {}
variable "core_storage_account_name" {}
variable "storage_account_url" {}
variable "function_app_default_hostname" {}
variable "function_app_name" {}
variable "environment" {}
variable "tags" {}
variable "fap_pe_name" {}
variable "fap_id" {}
variable "vault_private_endpoint_name" {}
