
variable "sanursery" {}
variable "core_rg" {}
variable "ch_rg_name" {}
variable "ch_rg_location" {}
variable "location" {}
variable "sanursery_pe_name_file" {}
variable "sanursery_pe_name_blob" {}
variable "core_pe_subnet_id" {}
variable "ch_pe_subnet_id" {}
variable "blob_private_dns_zone_name" {}
variable "gitlab_resource_group_name" {}
variable "tags" {}
variable "environment" {}
variable "fapp_storage_acc_name" {}
variable "blob_pe_to_fap_name" {}
variable "file_pe_to_fap_name" {}
variable "table_pe_to_fap_name" {}
variable "queue_pe_to_fap_name" {}
variable "queue_private_dns_zone_name" {}
variable "file_private_dns_zone_name" {}
variable "table_private_dns_zone_name" {}
variable "lss_function_app_name" {}
variable "crs_function_app_name" {}
variable "inv_wq_function_app_name" {}
variable "inv_lss_function_app_name" {}
variable "inv_ml_function_app_name" {}
variable "wq_function_app_name" {}
variable "inv_storage_name" {}
variable "lss_hist_pe_name_file" {}
variable "lss_hist_pe_name_blob" {}
variable "inv_pe_name_blob" {}
variable "inv_pe_name_file" {}
variable "inv_pe_subnet_id" {}

variable "lss_hist_storage_name" {}
variable "lss_pe_subnet_id" {}
variable "lss_hist_function_app_name" {}
variable "ml_hist_storage_name" {}
variable "ml_hist_pe_name_file" {}
variable "ml_hist_pe_name_blob" {}
variable "ml_pe_subnet_id" {}
variable "ml_hist_function_app_name" {}
variable "ml_function_app_name" {}
variable "inv_pe_name_table" {}
variable "inv_pe_name_queue" {}
variable "lss_hist_pe_name_table" {}
variable "lss_hist_pe_name_queue" {}
variable "ml_hist_pe_name_table" {}
variable "ml_hist_pe_name_queue" {}