variable "batch_primary_access_key" {}
variable "kafka_access_primary_key" {}
variable "lss_password" {}
variable "key_vault_id" {}
variable "db_user" {}
variable "db_passwd" {}
variable "db_name" {}
variable "reportingdb" {}
variable "pstgre_db_username" {}
variable "pstgre_db_password" {}
variable "reportingdb_admin" {}
variable "reportingdb_host" {}
variable "ml_batch_key" {}
variable "ml_cognito_username" {}
variable "ml_cognito_password" {}
variable "ml_kafka_access_key" {}
variable "ml_kafka_primary_key" {}
variable "ml_cognito_password_value" {}
variable "ml_cognito_username_value" {}
variable "ml_batch_primary_key" {}
variable "ml_function_app_access_key" {}
variable "ml_function_app_primary_key" {}
variable "function_app_name" {}
variable "core_rg_name" {}