variable "nsg_name" {}
variable "location" {}
variable "core_resource_group_name" {}
variable "environment" {}
variable "tags" {}
variable "sensor_db_subnet_id" {}
variable "sensor_batch_account_subnet_id" {}
variable "sensor_functionapp_subnet_id" {}
variable "ml_pe_subnet_id" {}
variable "sensor_bastion_subnet_id" {}
variable "ml_batch_account_subnet_id" {}
variable "ml_function_app_subnet_id" {}
variable "lss_batch_account_subnet_id" {}
variable "lss_pe_subnet_id" {}
variable "inv_vm_subnet_id" {}
variable "inv_db_subnet_id" {}
variable "inv_function_app_subnet_id" {}
variable "inv_pe_subnet_id" {}
variable "event_hub_pe_subnet_id" {}
variable "lss_function_app_subnet_id" {}
variable "sensor_pe_subnet_id" {}