variable "vnet_peering_sensor_name" {}
variable "vnet_peering_core_name" {}
variable "sensor_resource_group_name" {}
variable "sensor_vnet_virtual_network_name" {}
variable "remote_vnet_core_id" {}
variable "core_resource_group_name" {}
variable "core_virtual_network_name" {}
variable "sensor_dashboard_vnet_id" {}
variable "vnet_peering_gitlab_name" {}
variable "gitlab_vnet_name" {}
variable "gitlab_vnet_id" {}
variable "gitlab_resource_group_name" {}
variable "vnet_peering_kvap_name" {}
variable "kvap_rg_name" {}
variable "kvap_vnet_name" {}
variable "kvap_vnet_id" {}
variable "environment" {}
variable "vnet_peering_ch_name" {}
variable "vnet_ch_name" {}
variable "resource_group_ch_name" {}
variable "ch_vnet_id" {}
variable "vnet_connectivity_peering_name" {}
variable "connectivity_rg_name" {}
variable "connectivity_vnet_name" {}
variable "connectivity_vnet_id" {}
