variable "ss_preprod_alb_sg_name" {}
variable "vpc_id" {}
variable "ss_preprod_alb_sg_desc" {}
variable "ss_prod_alb_sg_name" {}
variable "ss_prod_alb_sg_desc" {}
variable "ss_preprod_sg_name" {}
variable "ss_preprod_sg_desc" {}
variable "ss_dev_alb_sg_name" {}
variable "ss_dev_alb_sg_desc" {}
variable "ss_dev_sg_name" {}
variable "ss_dev_sg_desc" {}
variable "ss_qa_alb_sg_name" {}
variable "ss_qa_alb_sg_desc" {}
variable "ss_qa_sg_name" {}
variable "ss_qa_sg_desc" {}
variable "ss_prod_sg_name" {}
variable "ss_prod_sg_desc" {}
variable "launch-wizard-5_name" {}
variable "launch-wizard-5_desc" {}
variable "qc-web-qa-SG_name" {}
variable "qc-web-qa-SG_desc" {}
variable "cliplibraryservice_qa_name" {}
variable "cliplibraryservice_qa_desc" {}
variable "bot_qa_name" {}
variable "bot_qa_desc" {}
variable "notifierservice_prod_name" {}
variable "notifierservice_prod_desc" {}
variable "qc_web_preprod_ALB_name" {}
variable "qc_web_preprod_ALB_desc" {}
variable "launch_wizard_2_name" {}
variable "launch_wizard_2_desc" {}
variable "service_dialog_ALB_QA_name" {}
variable "service_dialog_ALB_QA_desc" {}
variable "cliplibraryservice_preprod_name" {}
variable "cliplibraryservice_preprod_desc" {}
variable "qc_jenkins_name" {}
variable "qc_jenkins_desc" {}
variable "scoringservice_preprod_name" {}
variable "scoringservice_preprod_desc" {}
variable "embeddingscoring_qa_name" {}
variable "embeddingscoring_qa_desc" {}
variable "launch_wizard_4_name" {}
variable "launch_wizard_4_desc" {}
variable "test_cvazquez_deleteme_name" {}
variable "test_cvazquez_deleteme_desc" {}
variable "delete_me_name" {}
variable "delete_me_desc" {}
variable "qc_web_prod4_name" {}
variable "qc_web_prod4_desc" {}
variable "scoringservice_qa_name" {}
variable "scoringservice_qa_desc" {}
variable "service_dialog_sg_name" {}
variable "service_dialog_sg_desc" {}
variable "qc_worker_prod_alb_sg_name" {}
variable "qc_worker_prod_alb_sg_desc" {}
variable "scoringservice_prod_sg_name" {}
variable "scoringservice_prod_sg_desc" {}
variable "qc_sonar_sg_name" {}
variable "qc_sonar_sg_desc" {}
variable "dialogservice_memcache_sg_name" {}
variable "dialogservice_memcache_sg_desc" {}
variable "qc_web_preprod_sg_name" {}
variable "qc_web_preprod_sg_desc" {}
variable "qc_web_qa_alb_sg_name" {}
variable "qc_web_qa_alb_sg_desc" {}
variable "cliplibraryservice_dev_sg_name" {}
variable "cliplibraryservice_dev_sg_desc" {}
variable "qc_web_prod_ALB_SG_name" {}
variable "qc_web_prod_ALB_SG_desc" {}
variable "qc_web_preprod4_name" {}
variable "qc_web_preprod4_desc" {}
variable "" {}
variable "" {}
variable "" {}
variable "" {}
variable "" {}
variable "" {}