variable "core_resource_group_name" {}
variable "core_vnet_id" {}
variable "environment" {}
variable "core_batch_private_dns_name" {}
variable "core_batch_link_name" {}
variable "core_acr_private_dns_name" {}
variable "core_acr_link_name" {}
variable "core_fap_private_dns_name" {}
variable "core_network_name" {}
variable "core_file_dns_name" {}
variable "core_file_link_name" {}
variable "core_fap_dns_name" {}
variable "core_table_fap_dns_name" {}
variable "core_table_link_name" {}
variable "core_table_record_name" {}
variable "core_blob_link_name" {}
variable "core_vault_name" {}
variable "core_link_name" {}
variable "core_psql_dns_vnet_name" {}
variable "core_queue_fap_dns_name" {}
variable "core_queue_link_name" {}
variable "core_psql_dns_name" {}
variable "core_queue_record_name" {}
variable "tags" {}
